version: '3.4'

services:
  webapitodolist:
    image: ${DOCKER_REGISTRY-}webapitodolist
    build:
      context: .
      dockerfile: Dockerfile



  db:
    image: mysql
    environment:
        MYSQL_RANDOM_ROOT_PASSWORD: 1
        MYSQL_DATABASE: webapitodolistcontext
        MYSQL_USER: dbuser
        MYSQL_PASSWORD: dbuserpassword
    volumes:
       - dbdata:/var/lib/mysql
       - ./_MySQL_Init_Script:/docker-entrypoint-initdb.d
    restart: always
  webapitodolistcontextapp:
    depends_on:
        - db
    image: nurievilshat/webapitodolistcontext:runtime
    build:
        context: .
    ports:
        - "8000:5000"

volumes:
    dbdata:
    


